language: python
python:
  - '3.6'
  - pypy
before_install:
  - pip install --user poetry
install:
  - poetry install
script:
  - poetry run coverage run -m pytest
after_success:
  - poetry run mullpy
after_script:
  - poetry run coveralls
