language: python
python:
- '3.6'
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run coverage run -m pytest
after_success:
- poetry run mullpy
after_script:
- poetry run coveralls
before_deploy:
- poetry build
deploy:
  skip_cleanup: true
  provider: pypi
  user: franccesco
  password:
    secure: Fy6cMUD6Cd0a/QSCiJ4Ty1MwnXyKcIjP5dXH8udakvImDllTmUct1Kek57WDbEikuIgoe77h3uDkH+TiZ+zCoQkAmCbS4To2MDUbvZ5PcTyN024hR20FnpGtAoakxR6p1oBitCO+TvNp89DZKDXgdWIoeA7mMQXgAy0rXzn6ebFlrMlwTCdHuN7frqGo/HA/esbLRAeD2Ybxa5WrlAgWfaBwFdkgz6joVU/wQoIzQTLK5u6u9goh3inCQXmDinHF7WsSq0J9+M/qUi0TjolJxQ6KrgdMYsJVSQZ0eX3Mf3B2IhNCylZnvCGv06exvXSkhem1KQeXRKp2bJbszBli53lSbojMqBujKUUA6hkzoCbyGKE2x0fDKIEpP/55EubndYV/uAxWqLW0KD3v12gwBRiLGc65I7DpQM0mJxukzakk3fFvloQH6BPwkvDvtY8u8y5LenEm/82TjVM10NBNjQ3So+ykdEzZpGxwSVV6KgcEmJmPze3nyb+JNpeqZVSTvHw862jx5RQdiPPjOJDlPfhjlEPYHMDC6JnDP65lR5HBJhgoqBkBdsim+I8ltOwInOuo0rxArkKEdT5ud80PpXfPdJtMvu7aBiHanWhwX40PUQItKlDK8pJ/fDPaQ8B1q0uyWScBuOzmlTOLZlCwEBTTGKQOY4TosahSlI+DhNM=
  on:
    tags: true
    branch: master
after_deploy:
- deactivate
- pip install mullvad-python
- mullpy
notifications:
  slack:
    secure: Ov/NSsyY5RVNeed2gxuh+yLhKT/VgAPsS+xdBpq3pqlqcQ1/YzkaZSbemBCHVdtfJBwfnEAPONvGjV7DskgOA7E1dMguQKZaoQGE/SwRmKodViJ3mJy4JQ6bb6bzflLEmApvDkrOIMnKz3AV77a6gC1inwypF05lHQmfP9EoqFy9qPXtxwQ46Czg6N3cDn/453lysTcrJiLME1oru0zsxpkP+wRuDkuqspI9Fp2EtmL/2InRbAhhhWzc6w3ZRcL0pI/09jo25/Fnmn3WzRXgIzvtk4rVJ8zFxlmyoeCQqnlPJ/Pxo0kzehMaowU9wkLrQNg4gkVwg+ADPBN/YSO+FfgiYj5S2Td19Oc9V6Ex00da5ZSM4Gr9wIffwzMvBJV+jjPu9gINqeC70iU/R5iMlMHNNCng7llaTTefTuifqYHMt++18AtWFDIdEU9tNrwP0RalVhytQ2FL48/mN1vrTPPa2Blq/2l0r1dRHM9nzne6ZUOexk/ZgXi5QLNSMEuG+Zw1bEhllogfRvl1FuzWs1kCZXF5JdXGMNpIBKqLMMzVkeef0zQwcIE6LMlvGsEQgZRmsbilSLkV00bjsgxz+umRryPN5FAPi/0GZfogjpwO+h/jZjZ1GqKbHShIcKbzRTz7vGS46LkXPQnFzODw48g66blwlSlkWSf+jBnob6c=
